config/routes.rb
Rails.application.routes.draw do
  # root
  root 'welcome#index'
  #users and friends
  devise_for :users
  get 'search_friend', to: 'users#search_friend', as:'search_friend'
  get 'serve_search_friend', to: 'users#serve_search_friend', as: 'serve_search_friend'
  get 'my_friends', to: 'users#my_friends', as: 'my_friends'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  #address
  resource :address
  #books
  resources :books, except: [:new, :create, :destroy]
  get 'my_books', to: 'users#my_books', as: 'my_books'
  get 'search_book', to: 'books#search', as: 'search_book'
  get 'serve_book_search', to: 'books#serve_search', as: 'serve_book_search'
  get 'catalog_search', to: 'books#catalog_search', as: 'catalog_search'
  get 'book_to_add/:id', to: 'books#book_to_add', as: 'book_to_add'
  post 'add_book/:id', to: 'books#add_book', as: 'add_book'
  #wishlist
  resources :wishlists, only: [:create, :destroy]
  get 'my_wishlist', to: 'users#my_wishlist', as: 'my_wishlist'
  #shopping cart
  resources :shopping_carts, only: [:create, :destroy, :index]
  put 'update_cart', to: 'shopping_carts#update_cart', as: 'update_cart'
  post 'checkout', to: 'shopping_carts#checkout', as: 'checkout'
  post 'book_to_friend_checkout', to: 'shopping_carts#book_to_friend_checkout', as: 'book_to_friend_checkout'
  # gifts
  get 'my_gifts', to:'users#my_gifts', as: 'my_gifts'
  put 'already_seen', to:'users#already_seen', as: 'already_seen'
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :already_friends
  include PgSearch::Model

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :address
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :wishlists
  has_many :wish_books, through: :wishlists, source: 'book'
  has_many :shopping_carts
  has_many :cart_books, through: :shopping_carts, source: 'book'
  has_many :sales
  has_many :sale_books, through: :sales
  has_one_attached :avatar

  pg_search_scope :search_friend,
                  against: [:fullname, :email],
                  using: :dmetaphone

  validates_presence_of :fullname
  validates_presence_of :birth_date 

  def avatar_thumbnail
    avatar.variant(resize: "150x150!").processed 
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

  def already_in_wishlist?(book)
    self.wish_books.where(id:book).exists?
  end

  def already_in_cart?(book)
    self.cart_books.where(id:book).exists?
  end

  def self.search(friend, current_user)
    self.search_friend(friend).where.not(id: current_user).and(self.where(admin: false))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_friend, only: [ :show ]
    before_action :not_visit_current_user_page, only: [:show]
    before_action :not_visit_admin_user_page, only: [:show]
    rescue_from Exceptions::BaseException, :with => :render_error_response
    
    def search_friend
    end
  
    def serve_search_friend
      raise Exceptions::CustomExceptions::FriendError::MissingSearchTerms if params[:friend].blank?
      @friends = User.search(params[:friend], current_user)
      if !@friends.blank?
        @friends.each { |friend| friend.already_friends = current_user.not_friends_with?(friend.id) }
      end
      respond_to do |format|
        format.js { render partial: 'users/partials/friend_result' }
      end
    end

    def my_friends
      @friends = current_user.friends
    end

    def show
      @to_friend_checkout = ShoppingCart.new()
      @user.already_friends = current_user.not_friends_with?(@user.id)
      @owned_books = Book.joins(sale_books: :sale).where(sales: { user_id: @user.id }).or(Book.joins(sale_books: :sale).where(sales: { friend_id: @user.id })).distinct.paginate(page: params[:page], per_page: 5)
      @wishlist_books = @user.wish_books.paginate(page: params[:page], per_page: 5)
      if !@wishlist_books.blank?
        @wishlist_books.each do |book| 
          book.wish_book_owner = false
          book.price_details = Services::GetCartPrices.call(book)
          book.still_available = Book.still_available?(book)
        end
      end
    end

    def my_books
      @owned_books = Book.joins(sale_books: :sale).where(sales: { user_id: current_user.id, friend_id: nil }).or(Book.joins(sale_books: :sale).where(sales: { friend_id: current_user.id })).distinct.paginate(page: params[:page], per_page: 5)
    end

    def my_wishlist
      @wishlist_books = current_user.wish_books.paginate(page: params[:page], per_page: 5)
      if !@wishlist_books.blank?
        @wishlist_books.each { |book| book.wish_book_owner = true }
      end
    end

    def my_gifts
      @gifted_sales = Sale.includes( :user, { sale_books: :book } ).where('sales.friend_id = ? and view_flag = false', current_user.id).references(:user).paginate(page: params[:page], per_page: 5)
    end

    def already_seen
      @sale_book = SaleBook.new()
      salebook = SaleBook.where(sale_id: params[:sale_id], book_id: params[:book_id]).first
      if salebook.update_attribute(:view_flag, true)
        flash[:notice] = "Book notification removed"
      else 
        flash[:alert] = "Something went wrong trying to remove the book notification"
      end
      redirect_to my_gifts_path
    end

    private

    def set_friend
      @user = User.find(params[:id]) rescue not_found
    end

    def not_visit_current_user_page
      if current_user.id == @user.id
        flash[:alert] = "Can't access this page"
        redirect_to search_friend_path
      end 
    end

    def not_visit_admin_user_page
      if @user.admin?
        flash[:alert] = "Can't access this page"
        redirect_to search_friend_path
      end 
    end

    def render_error_response(error)
      @error = error 
      respond_to do |format|
        format.js { render partial: 'shared/ajax_error' }
      end
    end
end
  

app/views/users/_friend_result.html.erb
<% if !@friends.blank? && @friends.any? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col text-center">Full Name</th>
      <th scope="col text-center">Email</th>
      <th scope="col text-center" colspan = "2">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
        <tr class="my-3">
            <td><%= friend.fullname %></td>
            <td><%= friend.email %></td>
            <td><%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success' %></td>
            <% if friend.already_friends %>
                <td><%= link_to 'Add friend', friendships_path(friend: friend), class: 'btn btn-sm btn-primary', method: :post %></td>
            <% else %>
                <td>
                <span class="badge badge-secondary py-2 mt-1">
                    You are friends
                </span>
                </td>
            <% end %>
        </tr>
    <% end %>
  </tbody>
</table>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>

app/views/users/_wishlist.html.erb
<% if !obj.wish_books.blank? %>
    <% obj.wish_books.each do |book| %>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                    <img src=<%= book[:image_link] %> class="img-fluid my-4">
                </div>
                <div class="col-md-9 align-self-center">
                    <div class="card-body text-justify">
                        <div class="d-flex flex-column align-self-center">
                            <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book[:title] %> </h5>
                            <%= render 'books/partials/rating', obj:book[:average_rating]%>
                            <%= render 'books/partials/authors', obj: author_names(book.authors) %>
                            <div class="d-flex justify-content-center">
                                <%= link_to 'Buy Book to Friend', '#', class: "btn btn-success"%>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
    <% end %>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>

app/views/users/friends.html.erb
<h3 class="mb-4">Search Friends</h3>

<%= form_with url: search_friend_path, method: :get, local: false do |f| %>
    <div class="input-group mb-3">
        <%= f.text_field :friend, placeholder: 'Name or email', autofocus:true, class: 'form-control' %>
        <div class="input-group-append">
            <%= button_tag type: :submit, class: "btn btn-success", id:"button-addon2" do %>
                <%= fa_icon 'search' %> 
            <% end %>
        </div>
    </div>
<% end %>

<div id="errors"></div>
<div id="friend-result"></div>

<% if !@friends.empty? %>
    <%= render 'friends/list'%>
<% end %>

app/views/users/my_books.html.erb
<h3 class="mb-4">My Books</h3>
<%= render 'users/partials/owned_books'%>

app/views/users/my_friends.html.erb
<h3 class="mb-4 px-0">My Friends</h3>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th scope="col">Email</th>
            <th scope="col">Full Name</th>
            <th scope="col" colspan = "2">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @friends.each do |friend|%>
            <tr>
                <td><%= friend[:email] %></td>
                <td><%= friend[:fullname] %></td>
                <td>
                    <div class="d-flex">
                        <%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success' %>
                        <%= link_to 'Stop following', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning mx-2' %>
                    </div>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/users/my_gifts.html.erb
<h3 class="mb-4">Gifts</h3>
<% if !@gifted_sales.blank? %>
    <% @gifted_sales.each do |gifted_sale| %>
        <% gifted_sale.sale_books.each do |sale_book| %>
            <div class="card mb-3">
                <div class="alert alert-secondary text-center mt-4 mx-4">
                    The following user: <%= link_to gifted_sale.user.fullname, user_path(gifted_sale.user.id) %> has gifted you the following book:
                </div> 
                <h5 class="card-title text-center"><%= sale_book.book.title %></h5>
                <img src=<%= sale_book.book.image_link %> alt=<%= sale_book.book.title %> class="rounded mx-auto d-block mt-2 mb-4" style="width: 8rem"> 
                <div class="d-flex justify-content-center mb-4">
                    <%= link_to 'View', book_path(sale_book.book.id), class: "btn btn-primary"%>
                    <%= form_with(model: @book, url: already_seen_path, method: :put) do |f| %>
                        <%= f.hidden_field :sale_id, value: gifted_sale.id %>
                        <%= f.hidden_field :book_id, value: sale_book.book.id %>
                        <%= f.submit 'Already seen it', class: 'btn btn-warning mx-2' %>
                    <% end %>
                </div>
            </div> 
        <% end %>
    <% end %>
    <% if will_paginate @gifted_sales %>
        <div class="flickr_pagination mb-4">
            <%= will_paginate @gifted_sales, :container => false %>
        </div>
    <% end %>
<% else %>
    <%= render 'shared/nothing_found' %>
<%end%>

app/views/users/my_wishlist.html.erb
<h3 class="mb-4 px-0">My Wishlist</h3>
<%= render 'users/partials/wishlist' %>

app/views/users/search_friend.html.erb
<h3 class="mb-4">Search Friends</h3>

<%= form_with url: serve_search_friend_path, method: :get, local: false do |f| %>
    <div class="input-group mb-3">
        <%= f.text_field :friend, placeholder: 'Name or email', autofocus:true, class: 'form-control' %>
        <div class="input-group-append">
            <%= button_tag type: :submit, class: "btn btn-success", id:"button-addon2" do %>
                <%= fa_icon 'search' %> 
            <% end %>
        </div>
    </div>
<% end %>

<div id="errors"></div>
<div id="friend-result"></div>

app/views/users/show.html.erb
<%= link_to my_friends_path, class:"btn btn-link px-0 " do %>
  <%= fa_icon 'arrow-circle-left' %> Back
<% end %>

<div class="d-flex flex-column justify-content-center align-items-center">

    <div class="text-center mb-2">
        <% if @user.avatar.attached? %>
            <%= image_tag(@user.avatar, class:"rounded", style:"width: 8rem") %>
        <% else %>
            <%= fa_icon 'user 4x' %>
        <% end %>
    </div>

    <p class="text-center"><%= @user[:email] %></p>
    <p class="text-center"><%= @user[:fullname] %></p>
    <% if @user.already_friends %>
        <%= link_to 'Add friend', friendships_path(friend: @user), class: 'btn btn-sm btn-primary', method: :post %>
    <% else %>
        <%= link_to 'Stop following', friendship_path(@user), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-warning' %>
    <% end %>
</div>

<div class="d-flex flex-column justify-content-center mt-4">
    <ul class="nav nav-tabs mb-3">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#owned-books">Owned Books</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#wishlist-books">Wishlist</a>
        </li>
    </ul>

    <div class="tab-content">
        <div class="tab-pane container active" id="owned-books">
            <%= render 'users/partials/owned_books'%>
        </div>

        <div class="tab-pane container fade" id="wishlist-books">
            <%= render 'users/partials/wishlist' %>
        </div>
    </div>
</div>