config/routes.rb
Rails.application.routes.draw do
  # root
  root 'welcome#index'
  #users and friends
  devise_for :users
  get 'search_friend', to: 'users#search_friend', as:'search_friend'
  get 'serve_search_friend', to: 'users#serve_search_friend', as: 'serve_search_friend'
  get 'my_friends', to: 'users#my_friends', as: 'my_friends'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  #address
  resource :address
  #books
  resources :books, except: [:new, :create, :destroy]
  get 'my_books', to: 'users#my_books', as: 'my_books'
  get 'search_book', to: 'books#search', as: 'search_book'
  get 'serve_book_search', to: 'books#serve_search', as: 'serve_book_search'
  get 'catalog_search', to: 'books#catalog_search', as: 'catalog_search'
  get 'book_to_add/:id', to: 'books#book_to_add', as: 'book_to_add'
  post 'add_book/:id', to: 'books#add_book', as: 'add_book'
  #wishlist
  resources :wishlists, only: [:create, :destroy]
  get 'my_wishlist', to: 'users#my_wishlist', as: 'my_wishlist'
  #shopping cart
  resources :shopping_carts, only: [:create, :destroy, :index]
  put 'update_cart', to: 'shopping_carts#update_cart', as: 'update_cart'
  post 'checkout', to: 'shopping_carts#checkout', as: 'checkout'
  post 'book_to_friend_checkout', to: 'shopping_carts#book_to_friend_checkout', as: 'book_to_friend_checkout'
  # gifts
  get 'my_gifts', to:'users#my_gifts', as: 'my_gifts'
  put 'already_seen', to:'users#already_seen', as: 'already_seen'
end

app/models/book.rb
class Book < ApplicationRecord
    include PgSearch::Model

    attr_accessor :wish_book_owner, :already_in_wishlist, :already_in_cart, :price_details, :still_available

    has_many :book_authors
    has_many :authors, through: :book_authors
    has_many :wishlists
    has_many :wish_users, through: :wishlists, source: 'user'
    has_many :shopping_carts
    has_many :cart_users, through: :shopping_carts, source: 'user'
    has_many :sale_books
    
    pg_search_scope :search_book, 
    against: [:title, :publisher, :description],
    associated_against: {
        authors: :full_name
    },
    using: {
        tsearch: {dictionary: "english", prefix: true }
    }

    validates :purchase_price, presence: true, length: { minimum:1, maximum:7 }, numericality: { greater_than: 0, less_than: 10000 } 
    validates :sale_price, presence: true, length: { minimum:1, maximum:7 }, numericality: { greater_than: :purchase_price, message: 'must be greater than purchase price' }
    validates :sale_price, numericality: { less_than: 10000 }
    validates :stock, presence: true, length: { minimum:1, maximum:6 }, numericality: { only_integer: true, greater_than: 0, less_than: 100000 }
    validates :external_id, presence: true, uniqueness: { case_sensitive: false, message: "book has been already added" }

    before_save :sanitize_params

    def self.check_book(external_id)
        where(external_id: external_id).first
    end

    def self.check_book_availability(book, quantity)
        self.where(id: book).first.stock > 0 && self.where(id: book).first.stock >= quantity.to_i
    end

    def self.still_available?(book)
        self.where(id: book).first.stock > 0
    end

    private 
    def sanitize_params
        self.title = self.title.titleize
        self.stock = self.stock.to_i
        self.purchase_price = self.purchase_price.to_f
        self.sale_price = self.sale_price.to_f
        self.average_rating = self.average_rating.blank? ? nil : self[:average_rating].to_i
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [ :show, :edit, :update ]
  before_action :require_admin, only: [:search, :serve_search, :add_book, :book_to_add, :edit, :update]
  rescue_from Exceptions::BaseException, :with => :render_error_response

  def index
    @books = Book.paginate(page: params[:page], per_page: 5)
  end

  def catalog_search
    @search_books = Book.search_book(params[:book]).paginate(page: params[:page], per_page: 5) 
  end

  def show
    if !@book.blank?
      @book.already_in_wishlist = current_user.already_in_wishlist?(@book)
      @book.already_in_cart = current_user.already_in_cart?(@book)
      @book.still_available = Book.still_available?(@book)
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book 
      flash[:notice] = "Book was successfully updated"
    else
      render :edit
    end
  end

  def search
  end

  def serve_search 
    @api_books = Apis::GoogleApi::SearchBooks.volumes(params[:book])
    if !@api_books.blank?
      @api_books.each {|book| book["already_added"] = !Book.check_book(book["id"])}
    end
    respond_to do |format|
      format.js { render partial: 'books/partials/search_result' }
    end    
  end

  def book_to_add
    @book_model = Book.new
    @api_book = Apis::GoogleApi::SearchBooks.volume(params[:id])
  end

  def add_book
    @book_model = Book.new(book_params)
    params[:author][:full_names] = params[:author][:full_names] == "None" ? "Anonymous" : params[:author][:full_names].split(", ")
    if !params[:author][:full_names].blank?
      params[:author][:full_names].each do |full_name|
        author = Author.where(full_name: full_name.titleize).first_or_create(full_name: full_name.titleize)
        @book_model.authors << author
      end
    end
    if @book_model.save
      flash[:notice] = "Book was added successfully"
      redirect_to @book_model
    else 
      @api_book = Apis::GoogleApi::SearchBooks.volume(params[:id])
      render 'book_to_add' 
    end 
  end

  private
    def set_book
      @book = Book.find(params[:id]) rescue not_found
    end

    def book_params
      params.require(:book).permit(:id, :title, :description, :image_link, :average_rating, :publisher, :published_date, :preview_link, :stock, :purchase_price, :sale_price, :external_id)
    end    

    def require_admin
      if !current_user.admin?
        flash[:alert] = "Can't access this page"
        redirect_to books_path
      end
    end  

    def render_error_response(error)
      @error = error 
      respond_to do |format|
        format.js { render partial: 'shared/ajax_error' }
      end
    end
end

app/helpers/books_helper.rb
module BooksHelper


end

app/views/books/_result.html.erb
<% if !@books.blank? %>
    <% @books.each do |book|%>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                    <%= display_book_image(book["volumeInfo"]["imageLinks"], book["volumeInfo"]["title"]) %>
                </div>
                <div class="col-md-9">
                    <div class="card-body text-justify">
                        <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= display_book_text(book["volumeInfo"]["title"]) %> </h5>
                        <%= render 'rating', obj:book["volumeInfo"]["averageRating"]%>
                        <%= render 'authors', obj: book["volumeInfo"]["authors"]%>
                        <p class="card-text"><span class="font-weight-bold">Description: </span> <%= display_book_text(book["volumeInfo"]["description"]) %> </p>
                        <div class="d-flex justify-content-between">
                            <p class="card-text"><span class="font-weight-bold">Publisher: </span> <%= display_book_text(book["volumeInfo"]["publisher"]) %> </p>
                            <p class="card-text"><span class="font-weight-bold">Published Date: </span> <%= display_book_text(book["volumeInfo"]["publishedDate"])%></p>
                        </div>
                        <div class="d-flex justify-content-center">
                            <%= link_to 'Preview', book["volumeInfo"]["previewLink"], class: "btn btn-link mx-2", target: :_blank %>
                            <%= link_to 'Select', book_to_add_path(id: book["id"]), class: "btn btn-success mx-2" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% end %>

app/views/books/_search_result.html.erb
<% if !@api_books.blank? %>
    <% @api_books.each do |book| %>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                    <img src=<%= book_image_url(book["volumeInfo"]["imageLinks"])%> alt=<%= book_text(book["volumeInfo"]["title"])%> class="img-fluid mt-4">
                </div>
                <div class="col-md-9">
                    <div class="card-body text-justify">
                        <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book_text(book["volumeInfo"]["title"]) %> </h5>
                        <%= render 'rating', obj:book["volumeInfo"]["averageRating"]%>
                        <%= render 'authors', obj: book["volumeInfo"]["authors"]%>
                        <p class="card-text"><span class="font-weight-bold">Description: </span> <%= book_text(book["volumeInfo"]["description"]) %> </p>
                        <div class="d-flex justify-content-between">
                            <p class="card-text"><span class="font-weight-bold mr-2">Publisher: </span> <%= book_text(book["volumeInfo"]["publisher"]) %> </p>
                            <p class="card-text"><span class="font-weight-bold">Published Date: </span> <%= book_text(book["volumeInfo"]["publishedDate"])%></p>
                        </div>
                        <div class="d-flex justify-content-center">
                            <%= link_to 'Preview', book["volumeInfo"]["previewLink"], class: "btn btn-link mx-2", target: :_blank %>
                            <% if book["already_added"] %>
                                <%= link_to 'Select', book_to_add_path(id: book["id"]), class: "btn btn-success mx-2" %>
                            <% else %>
                                <span class="badge badge-pill badge-secondary"><p class="pt-3 pb-0">You have already added this book</p></span>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
<% else %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        Nothing found 
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/books/book_to_add.html.erb
<%= link_to search_book_path, class:"btn btn-link px-0 " do %>
  <%= fa_icon 'arrow-circle-left' %> Back
<% end %>
<% if !@api_book.blank? %>
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                <%= image_tag(book_image_url(@api_book["volumeInfo"]["imageLinks"]), alt: book_text(@api_book["volumeInfo"]["title"]), class:"img-fluid mt-4") %>
            </div>
            <div class="col-md-9">
                <div class="card-body text-justify">
                    <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book_text(@api_book["volumeInfo"]["title"]) %> </h5>
                    <%= render 'books/partials/rating', obj:@api_book["volumeInfo"]["averageRating"]%>
                    <%= render 'books/partials/authors', obj:@api_book["volumeInfo"]["authors"]%>
                    <p class="card-text"><span class="font-weight-bold">Description: </span> <%= book_text(@api_book["volumeInfo"]["description"]) %> </p>
                    <div class="d-flex justify-content-between">
                        <p class="card-text"><span class="font-weight-bold mr-2">Publisher: </span> <%= book_text(@api_book["volumeInfo"]["publisher"]) %> </p>
                        <p class="card-text"><span class="font-weight-bold">Published Date: </span> <%= book_text(@api_book["volumeInfo"]["publishedDate"])%></p>
                    </div>
                    <div class="d-flex flex-column justify-content-center align-items-center my-2">
                        <%= form_with(model: @book_model, url: add_book_path(params[:id])) do |f| %>
                            <%= f.hidden_field :external_id, value: @api_book["id"] %>
                            <%= f.hidden_field :title, value: book_text(@api_book["volumeInfo"]["title"]) %>
                            <%= f.hidden_field :description, value: book_text(@api_book["volumeInfo"]["description"]) %>
                            <%= f.hidden_field :image_link, value: book_image_url(@api_book["volumeInfo"]["imageLinks"]) %>
                            <%= f.hidden_field :average_rating, value: @api_book["volumeInfo"]["averageRating"] %>
                            <%= f.hidden_field :publisher, value: book_text(@api_book["volumeInfo"]["publisher"]) %>
                            <%= f.hidden_field :published_date, value: book_text(@api_book["volumeInfo"]["publishedDate"]) %>
                            <%= f.hidden_field :preview_link, value: book_text(@api_book["volumeInfo"]["previewLink"]) %>

                            <%= fields_for :author, @book_model.authors do |f_author| %>
                                <%= f_author.hidden_field :full_names, value: format_authors(@api_book["volumeInfo"]["authors"])%>
                            <% end %>

                            <div class="form-group row">
                                <div class="col-sm-5">
                                    <%= f.label :purchase_price, 'Purchase price:', class: "form-label font-weight-bold" %>
                                </div>

                                <div class="col-sm-7">
                                    <%= f.text_field :purchase_price, class: "form-control"%>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-5">
                                    <%= f.label :sale_price, 'Sale price:', class: "form-label font-weight-bold" %>
                                </div>

                                <div class="col-sm-7">
                                    <%= f.text_field :sale_price, class: "form-control"%>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-5">
                                    <%= f.label :stock, 'Stock:', class: "form-label font-weight-bold" %>
                                </div>

                                <div class="col-sm-7">
                                    <%= f.number_field :stock, value:"1", in: 1..100000, class: "form-control"%>
                                </div>
                            </div>
                            
                            <div class="text-center">
                                <%= f.submit("Save", class:"btn btn-primary mt-2")%>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%= render 'shared/form_errors', obj: @book_model %>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>

app/views/books/catalog_search.html.erb
<%= link_to books_path, class:"btn btn-link px-0 " do %>
  <%= fa_icon 'arrow-circle-left' %> Back to All Books
<% end %>

<div class="mt-3 mb-4">
    <%= render 'books/partials/search_catalog_form' %>
</div>
<p class="font-weight-bold">Search results for: <span class="font-weight-normal"><%= params[:book] %></span></p>

<% if !@search_books.blank? %>
    <% @search_books.each do |book| %>
        <div class="card mb-3">
            <div class="row no-gutters">
            <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                <img src=<%= book[:image_link] %> class="img-fluid my-4">
            </div>
            <div class="col-md-9 align-self-center">
                <div class="card-body text-justify">
                <div class="d-flex flex-column align-self-center">
                <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book[:title] %> </h5>
                <%= render 'books/partials/rating', obj:book[:average_rating]%>
                <%= render 'books/partials/authors', obj: author_names(book.authors) %>
                <div class="d-flex justify-content-center">
                    <%= link_to 'View', book_path(book), class: "btn btn-primary"%>
                </div>
                </div>
                </div>
            </div>
            </div>  
        </div>
    <% end %>
    <% if will_paginate @search_books%>
        <div class="flickr_pagination mb-4">
            <%= will_paginate @search_books, :container => false %>
        </div>
    <% end %>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>

app/views/books/edit.html.erb
<%= link_to books_path, class:"btn btn-link px-0 " do %>
  <%= fa_icon 'arrow-circle-left' %> Back
<% end %>
<% if !@book.blank? %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
        <img src=<%= @book[:image_link] %> alt=<%= @book[:title] %> class="img-fluid mt-4">
      </div>
      <div class="col-md-9">
        <div class="card-body text-justify">
          <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= @book[:title] %> </h5>
          <%= render 'books/partials/rating', obj:@book[:average_rating] %>
          <%= render 'books/partials/authors', obj: author_names(@book.authors) %>
          <p class="card-text"><span class="font-weight-bold">Description: </span> <%= book_text(@book[:description]) %> </p>
          <div class="d-flex justify-content-between">
            <p class="card-text"><span class="font-weight-bold mr-2">Publisher: </span> <%= @book[:publisher] %> </p>
            <p class="card-text"><span class="font-weight-bold">Published Date: </span> <%= @book[:published_date] %></p>
          </div>
          <%= form_with(model: @book, local: true) do |f| %>
            <div class="form-group row">
                <div class="col-sm-5">
                  <%= f.label :purchase_price, 'Purchase price:', class: "form-label font-weight-bold" %>
                </div>

                <div class="col-sm-7">
                  <%= f.text_field :purchase_price, class: 'form-control', value: (number_with_precision(f.object.purchase_price, :precision => 2) || 0) %>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                  <%= f.label :sale_price, 'Sale price:', class: "form-label font-weight-bold" %>
                </div>

                <div class="col-sm-7">
                  <%= f.text_field :sale_price, class: 'form-control', value: (number_with_precision(f.object.sale_price, :precision => 2) || 0) %>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                  <%= f.label :stock, 'Stock:', class: "form-label font-weight-bold" %>
                </div>

                <div class="col-sm-7">
                  <%= f.number_field :stock, in: 1..100000, class: "form-control"%>
                </div>
            </div>
            
            <div class="text-center">
              <%= f.submit("Update", class:"btn btn-primary mt-2")%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/form_errors', obj: @book %>
<% else %>
  <%= render 'shared/nothing_found' %>
<% end %>

app/views/books/index.html.erb
<h3 class="mb-4">All Books</h3>

<%= render 'books/partials/search_catalog_form' %>
<div id="errors"></div>
<div id="books-results">
  <% @books.each do |book| %>
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
          <img src=<%= book[:image_link] %> alt=<%= book[:title] %> class="img-fluid mt-4">
        </div>
        <div class="col-md-9 align-self-center">
          <div class="card-body text-justify">
          <div class="d-flex flex-column align-self-center">
            <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book[:title] %> </h5>
            <%= render 'books/partials/rating', obj:book[:average_rating]%>
            <%= render 'books/partials/authors', obj: author_names(book.authors) %>
            <p class="card-text"><span class="font-weight-bold mr-2">Price: </span> <%= number_to_currency(book[:sale_price]) %></p>
            <div class="d-flex justify-content-center">
              <%= link_to 'View', book_path(book), class: "btn btn-primary"%>
            </div>
          </div>
          </div>
        </div>
      </div>  
    </div>
  <% end %>
  <% if will_paginate @books %>
    <div class="flickr_pagination mb-4">
      <%= will_paginate @books, :container => false %>
    </div>
  <% end %>
</div>

app/views/books/search.html.erb
<h3 class="mb-4">Search Books</h3>

<%= form_with url: serve_book_search_path, method: :get, local: false do |f| %>
    <div class="input-group mb-3">
        <%= f.text_field :book, placeholder: "Book's search terms", autofocus:true, id:"search-input", class: 'form-control' %>
        <div class="input-group-append">
            <%= button_tag type: :submit, class: "btn btn-success", id:"button-addon2" do %>
                <%= fa_icon 'search' %> 
            <% end %>
        </div>
    </div>
<% end %>

<div id="errors"></div>

<div id="books-results"></div>

app/views/books/show.html.erb
<%= link_to books_path, class:"btn btn-link px-0 " do %>
  <%= fa_icon 'arrow-circle-left' %> Back
<% end %>
<% if !@book.blank? %>
  <div class="card mb-3">
    <% if !@book.still_available %>
      <div class="alert alert-danger d-flex flex-column align-items-center justify-content-center mx-4 mt-4" role="alert">
        We're sorry there are no units left for this book
      </div>
    <% end %>
    <div class="row no-gutters">
      <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
        <img src=<%= @book[:image_link] %> alt=<%= @book[:title] %> class="img-fluid mt-4">
      </div>
      <div class="col-md-9">
        <div class="card-body text-justify">
          <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= @book[:title] %> </h5>
          <%= render 'books/partials/rating', obj:@book[:average_rating] %>
          <%= render 'books/partials/authors', obj: author_names(@book.authors) %>
          <p class="card-text"><span class="font-weight-bold">Description: </span> <%= book_text(@book[:description]) %> </p>
          <div class="d-flex justify-content-between">
            <p class="card-text"><span class="font-weight-bold mr-2">Publisher: </span> <%= @book[:publisher] %> </p>
            <p class="card-text"><span class="font-weight-bold">Published Date: </span> <%= @book[:published_date] %></p>
          </div>
          <div class="d-flex flex-column justify-content-center align-items-center">
            <% if !current_user.admin %>
              <p class="card-text"><span class="font-weight-bold mr-2">Price: </span> <%= number_to_currency(@book[:sale_price]) %> </p>
            <% else %>
              <p class="card-text"><span class="font-weight-bold mr-2"> Purchase price: </span> <%= number_to_currency(@book[:purchase_price]) %></p>
              <p class="card-text"><span class="font-weight-bold mr-2"> Sale price: </span> <%= number_to_currency(@book[:sale_price]) %> </p>
              <p class="card-text"><span class="font-weight-bold mr-2"> Stock: </span> <%= @book[:stock] %></p>
            <% end %>
          </div>

          <% if !current_user.admin %>
            <div class="d-flex justify-content-center align-items-center my-3">
              <% if !@book.already_in_cart %>
                <% if @book.still_available %>
                  <%= form_with(model: @book, url: shopping_carts_path, method: :post) do |f| %>
                    <%= f.hidden_field :book_id, value: params[:id]%>
                    <%= f.hidden_field :price, value: @book[:sale_price] %>
                    <div class="form-group row">
                      <div class="col-sm-5">
                        <%= f.label :quantity, 'Quantity:', class: "form-label font-weight-bold" %>
                      </div>
                      <div class="col-sm-7">
                        <%= f.select(:quantity, (1..@book[:stock]), { selected: "1" }, { class: 'form-control' }) %>
                      </div>
                    </div>      
                    <div class="text-center">
                      <%= f.submit("Add to shopping cart", class:"btn btn-success mx-2")%>
                    </div>
                  <% end %>
                <% end %>
              <% else %>
                <span class="badge badge-secondary d-flex align-items-center py-2">
                  Book already added in shopping cart
                </span>
              <% end %>
            </div>
            
            <div class="d-flex justify-content-center mt-4">
              <%= link_to @book[:preview_link], class: "btn btn-primary mx-2", target: :_blank do %>
                <%= fa_icon 'eye', text:"Preview" %>
              <% end %>

              <% if !@book.already_in_wishlist %>
                <%= link_to wishlists_path(book: @book) , class: "btn btn-danger mx-2", method: :post do %>
                  <%= fa_icon 'heart', text:"Add to Wishlist" %>
                <% end %>
              <% else %>
                <span class="badge badge-secondary d-flex align-items-center">
                  Book already added in wishlist
                </span>
              <% end %>
            </div>
          <% else %>     
            <div class="text-center mt-4">
              <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-primary"%>
            </div> 
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/nothing_found' %>
<% end %>