config/routes.rb
Rails.application.routes.draw do
  # root
  root 'welcome#index'
  #users and friends
  devise_for :users
  get 'search_friend', to: 'users#search_friend', as:'search_friend'
  get 'serve_search_friend', to: 'users#serve_search_friend', as: 'serve_search_friend'
  get 'my_friends', to: 'users#my_friends', as: 'my_friends'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  #address
  resource :address
  #books
  resources :books, except: [:new, :create, :destroy]
  get 'my_books', to: 'users#my_books', as: 'my_books'
  get 'search_book', to: 'books#search', as: 'search_book'
  get 'serve_book_search', to: 'books#serve_search', as: 'serve_book_search'
  get 'catalog_search', to: 'books#catalog_search', as: 'catalog_search'
  get 'book_to_add/:id', to: 'books#book_to_add', as: 'book_to_add'
  post 'add_book/:id', to: 'books#add_book', as: 'add_book'
  #wishlist
  resources :wishlists, only: [:create, :destroy]
  get 'my_wishlist', to: 'users#my_wishlist', as: 'my_wishlist'
  #shopping cart
  resources :shopping_carts, only: [:create, :destroy, :index]
  put 'update_cart', to: 'shopping_carts#update_cart', as: 'update_cart'
  post 'checkout', to: 'shopping_carts#checkout', as: 'checkout'
  post 'book_to_friend_checkout', to: 'shopping_carts#book_to_friend_checkout', as: 'book_to_friend_checkout'
  # gifts
  get 'my_gifts', to:'users#my_gifts', as: 'my_gifts'
  put 'already_seen', to:'users#already_seen', as: 'already_seen'
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :already_friends
  include PgSearch::Model

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :address
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :wishlists
  has_many :wish_books, through: :wishlists, source: 'book'
  has_many :shopping_carts
  has_many :cart_books, through: :shopping_carts, source: 'book'
  has_many :sales
  has_many :sale_books, through: :sales
  has_one_attached :avatar

  pg_search_scope :search_friend,
                  against: [:fullname, :email],
                  using: :dmetaphone

  validates_presence_of :fullname
  validates_presence_of :birth_date 

  def avatar_thumbnail
    avatar.variant(resize: "150x150!").processed 
  end

  def not_friends_with?(id_of_friend)
    !self.friends.where(id: id_of_friend).exists?
  end

  def already_in_wishlist?(book)
    self.wish_books.where(id:book).exists?
  end

  def already_in_cart?(book)
    self.cart_books.where(id:book).exists?
  end

  def self.search(friend, current_user)
    self.search_friend(friend).where.not(id: current_user).and(self.where(admin: false))
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_friend, only: [ :show ]
    before_action :not_visit_current_user_page, only: [:show]
    before_action :not_visit_admin_user_page, only: [:show]
    rescue_from Exceptions::BaseException, :with => :render_error_response
    
    def search_friend
    end
  
    def serve_search_friend
      raise Exceptions::CustomExceptions::FriendError::MissingSearchTerms if params[:friend].blank?
      @friends = User.search(params[:friend], current_user)
      if !@friends.blank?
        @friends.each { |friend| friend.already_friends = current_user.not_friends_with?(friend.id) }
      end
      respond_to do |format|
        format.js { render partial: 'users/partials/friend_result' }
      end
    end

    def my_friends
      @friends = current_user.friends
    end

    def show
      @to_friend_checkout = ShoppingCart.new()
      @user.already_friends = current_user.not_friends_with?(@user.id)
      @owned_books = Book.joins(sale_books: :sale).where(sales: { user_id: @user.id }).or(Book.joins(sale_books: :sale).where(sales: { friend_id: @user.id })).distinct.paginate(page: params[:page], per_page: 5)
      @wishlist_books = @user.wish_books.paginate(page: params[:page], per_page: 5)
      if !@wishlist_books.blank?
        @wishlist_books.each do |book| 
          book.wish_book_owner = false
          book.price_details = Services::GetCartPrices.call(book)
          book.still_available = Book.still_available?(book)
        end
      end
    end

    def my_books
      @owned_books = Book.joins(sale_books: :sale).where(sales: { user_id: current_user.id, friend_id: nil }).or(Book.joins(sale_books: :sale).where(sales: { friend_id: current_user.id })).distinct.paginate(page: params[:page], per_page: 5)
    end

    def my_wishlist
      @wishlist_books = current_user.wish_books.paginate(page: params[:page], per_page: 5)
      if !@wishlist_books.blank?
        @wishlist_books.each { |book| book.wish_book_owner = true }
      end
    end

    def my_gifts
      @gifted_sales = Sale.includes( :user, { sale_books: :book } ).where('sales.friend_id = ? and view_flag = false', current_user.id).references(:user).paginate(page: params[:page], per_page: 5)
    end

    def already_seen
      @sale_book = SaleBook.new()
      salebook = SaleBook.where(sale_id: params[:sale_id], book_id: params[:book_id]).first
      if salebook.update_attribute(:view_flag, true)
        flash[:notice] = "Book notification removed"
      else 
        flash[:alert] = "Something went wrong trying to remove the book notification"
      end
      redirect_to my_gifts_path
    end

    private

    def set_friend
      @user = User.find(params[:id]) rescue not_found
    end

    def not_visit_current_user_page
      if current_user.id == @user.id
        flash[:alert] = "Can't access this page"
        redirect_to search_friend_path
      end 
    end

    def not_visit_admin_user_page
      if @user.admin?
        flash[:alert] = "Can't access this page"
        redirect_to search_friend_path
      end 
    end

    def render_error_response(error)
      @error = error 
      respond_to do |format|
        format.js { render partial: 'shared/ajax_error' }
      end
    end
end
  

app/views/users/partials/_friend_result.html.erb
<% if !@friends.blank? && @friends.any? %>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col text-center">Full Name</th>
        <th scope="col text-center">Email</th>
        <th scope="col text-center" colspan = "2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <tr class="my-3">
          <td><%= friend[:fullname] %></td>
          <td><%= friend[:email] %></td>
          <td><%= link_to 'View Profile', user_path(friend), class: 'btn btn-sm btn-success' %></td>
          <% if friend.already_friends %>
            <td><%= link_to 'Add friend', friendships_path(friend: friend), class: 'btn btn-sm btn-primary', method: :post %></td>
          <% else %>
            <td>
              <span class="badge badge-secondary py-2 mt-1">
                You are friends
              </span>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>

app/views/users/partials/_friend_result.js.erb
document.querySelector('#friend-result').innerHTML = "<%= j render(partial: 'users/partials/friend_result', formats: [:html]) %>"

app/views/users/partials/_owned_books.html.erb
<% if !@owned_books.blank? %>
  <% @owned_books.each do |owned_book| %>
    <div class="card mb-3">
      <div class="row no-gutters">
        <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
          <img src=<%= owned_book[:image_link] %> alt=<%= owned_book[:title] %> class="img-fluid mt-4">
        </div>
        <div class="col-md-9 align-self-center">
          <div class="card-body text-justify">
            <div class="d-flex flex-column align-self-center">
              <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= owned_book[:title] %> </h5>
              <%= render 'books/partials/rating', obj:owned_book[:average_rating]%>
              <%= render 'books/partials/authors', obj: author_names(owned_book.authors) %>
              <p class="card-text"><span class="font-weight-bold mr-2">Price: </span> <%= number_to_currency(owned_book[:sale_price]) %></p>
              <div class="d-flex justify-content-center">
                <%= link_to 'View', book_path(owned_book), class: "btn btn-primary"%>
              </div>
            </div>
          </div>
        </div>
      </div>  
    </div>
  <% end %>
  <% if will_paginate @owned_books %>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @owned_books, :container => false %>
    </div>
  <% end %>
<% else %>
  <%= render 'shared/nothing_found' %>
<% end %>

app/views/users/partials/_wishlist.html.erb
<% if !@wishlist_books.blank? %>
    <% @wishlist_books.each do |book| %>
        <div class="card mb-3">
            <div class="row no-gutters">
                <div class="d-flex flex-column align-items-center justify-content-center col-md-3">
                    <img src=<%= book[:image_link] %> class="img-fluid my-4">
                </div>
                <div class="col-md-9 align-self-center">
                    <div class="card-body text-justify">
                        <div class="d-flex flex-column align-self-center">
                            <h5 class="card-title"><span class="font-weight-bold">Title: </span> <%= book[:title] %> </h5>
                            <%= render 'books/partials/rating', obj:book[:average_rating]%>
                            <%= render 'books/partials/authors', obj: author_names(book.authors) %>
                            <p class="card-text"><span class="font-weight-bold mr-2">Price: </span> <%= number_to_currency(book[:sale_price]) %></p>
                            <div class="d-flex justify-content-center">
                                <% if !book.wish_book_owner %>
                                    <% if book.still_available %>
                                        <% if !@user.blank? && !@user.already_friends %>
                                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#buyBookModal" data-whatever="<%= [ book.to_json, book.price_details.to_json, @user.to_json ] %>">
                                                Buy Book to Friend
                                            </button>
                                        <% end %>
                                    <% else %>
                                        <div class="alert alert-danger d-flex flex-column align-items-center justify-content-center mx-4 mt-4" role="alert">
                                            We're sorry there are no units left for this book
                                        </div>
                                    <% end %>
                                <% else %>
                                    <%= link_to 'View', book_path(book), class: "btn btn-primary"%>
                                    <%= link_to 'Delete', wishlist_path(book), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger mx-2' %>
                                <% end %>    
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
        </div>
    <% end %>
    <div class="modal fade" id="buyBookModal" tabindex="-1" role="dialog" aria-labelledby="buyBookModalTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="buyBookModalTitle">Buy book to friend</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <%= form_with(id:"friend_checkout", model: @to_friend_checkout, url: book_to_friend_checkout_path, local: true) do |f| %>
                        <%= f.submit("Proceed to checkout", class:"btn btn-success")%>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <% if will_paginate @wishlist_books %>
        <div class="flickr_pagination mb-4">
            <%= will_paginate @wishlist_books, :container => false %>
        </div>
    <% end %>
<% else %>
    <%= render 'shared/nothing_found' %>
<% end %>