config/routes.rb
Rails.application.routes.draw do
  # root
  root 'welcome#index'
  #users and friends
  devise_for :users
  get 'search_friend', to: 'users#search_friend', as:'search_friend'
  get 'serve_search_friend', to: 'users#serve_search_friend', as: 'serve_search_friend'
  get 'my_friends', to: 'users#my_friends', as: 'my_friends'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
  #address
  resource :address
  #books
  resources :books, except: [:new, :create, :destroy]
  get 'my_books', to: 'users#my_books', as: 'my_books'
  get 'search_book', to: 'books#search', as: 'search_book'
  get 'serve_book_search', to: 'books#serve_search', as: 'serve_book_search'
  get 'catalog_search', to: 'books#catalog_search', as: 'catalog_search'
  get 'book_to_add/:id', to: 'books#book_to_add', as: 'book_to_add'
  post 'add_book/:id', to: 'books#add_book', as: 'add_book'
  #wishlist
  resources :wishlists, only: [:create, :destroy]
  get 'my_wishlist', to: 'users#my_wishlist', as: 'my_wishlist'
  #shopping cart
  resources :shopping_carts, only: [:create, :destroy, :index]
  put 'update_cart', to: 'shopping_carts#update_cart', as: 'update_cart'
  post 'checkout', to: 'shopping_carts#checkout', as: 'checkout'
  post 'book_to_friend_checkout', to: 'shopping_carts#book_to_friend_checkout', as: 'book_to_friend_checkout'
  # gifts
  get 'my_gifts', to:'users#my_gifts', as: 'my_gifts'
  put 'already_seen', to:'users#already_seen', as: 'already_seen'
end

app/views/layouts/_api_errors.html.erb
<% if !@error.blank?%>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        code: <%= @error.code%>, message: <%= @error.message %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if @errors.any? %>
    <% @errors.each do |error| %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        status: <%= error[:status]%>, code: <%= error[:code]%>, message: <%= error[:title]%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<p class="col-md-4 mb-0 text-muted text-center">© 2021 Magic Books Store, Inc</p>
<p class="col-md-5 mb-0 text-muted text-center">All rights reserved</p>
<ul class=" d-flex col-md-3 mb-0 justify-content-center">
    <%= link_to '#', class:"nav-link resized px-2 text-muted" do %>
        <%= fa_icon 'facebook' %> 
    <% end %>
    <%= link_to '#', class:"nav-link resized px-2 text-muted" do %>
        <%= fa_icon 'instagram' %> 
    <% end %>
    <%= link_to '#', class:"nav-link resized px-2 text-muted" do %>
        <%= fa_icon 'twitter' %> 
    <% end %>
    <%= link_to '#', class:"nav-link resized pl-2 text-muted" do %>
        <%= fa_icon 'whatsapp' %> 
    <% end %>
</ul>

app/views/layouts/_messages.html.erb
<% if notice %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <% if current_user && current_user.admin %>
            <%= link_to 'Magic Books (Admin)', root_path, class:'navbar-brand'%>
        <% else %>
            <%= link_to 'Magic Books', root_path, class:'navbar-brand'%>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if current_user %>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= fa_icon 'book', text:"Books" %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <% if current_user.admin %>
                                <%= link_to search_book_path, class:"dropdown-item" do %>
                                    <%= fa_icon 'plus-circle', text:"Add book" %> 
                                <% end %>
                            <% end %>
                            <%= link_to books_path, class:"dropdown-item" do %>
                                <%= fa_icon 'list-ul', text:'All Books' %>
                            <% end %>
                            <% if !current_user.admin %>
                                <%= link_to my_books_path, class:"dropdown-item" do %>
                                    <%= fa_icon 'book', text:'My Books' %>
                                <% end %>
                            <% end %>
                        </div>
                    </li>
                    <% if !current_user.admin %>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%= fa_icon 'users', text:"Friends" %>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <%= link_to search_friend_path, class:"dropdown-item" do %>
                                    <%= fa_icon 'search', text:'Search friends'%>
                                <% end %>
                                <%= link_to my_friends_path, class:"dropdown-item" do %>
                                    <%= fa_icon 'users', text: 'My friends' %>
                                <% end %>
                            </div>
                        </li>
                        <li class="nav-item">
                            <%= link_to my_gifts_path, class: 'nav-link' do %>
                                <%= fa_icon 'gift', text: 'Gifts' %>
                            <% end %>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <%= fa_icon 'user', text: current_user.email %>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to my_wishlist_path, class:"dropdown-item" do %>
                                <%= fa_icon 'heart', text:"My wishlist" %> 
                            <% end %>
                            <%= link_to edit_user_registration_path, class:"dropdown-item" do %>
                                <%= fa_icon 'edit', text: "Edit Profile" %>
                            <% end %>
                            <%if !current_user.address.blank? %>
                                <%= link_to edit_address_path, class:"dropdown-item" do %>
                                    <%= fa_icon 'edit', text:"Edit Shipping Address" %> 
                                <% end %>
                            <% end %>
                            <%= link_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
                                <%= fa_icon 'sign-out', text:"LogOut" %> 
                            <% end %>
                        </div>
                        </li>
                    <% end %>
                </ul>
                <ul class="navbar-nav ml-auto">
                <% if !current_user.admin %>
                    <li class="nav-item mt-2 mr-0">
                        <%= link_to shopping_carts_path, class:"nav-link" do %>
                            <%= fa_icon 'shopping-cart', text: "Cart" %>
                        <% end %>
                    </li>
                <% else %>
                    <%= link_to destroy_user_session_path, class: 'btn btn-danger', method: :delete do %>
                        <%= fa_icon 'sign-out', text:"LogOut" %> 
                    <% end %>
                <% end %>
                </ul>
            <% else %>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <%= link_to 'Sign In', new_user_session_path, class: "mx-2 my-1 nav-link text-white btn btn-primary" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign Up', new_user_registration_path, class: "mx-2 my-1 nav-link text-white btn btn-secondary" %>
                    </li>
                </ul>
            <% end %> 
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magic Books App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column min-vh-100" >
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main class="container my-3">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </main>

    <footer class="mt-auto footer-position d-flex flex-wrap justify-content-between align-items-center py-3 my-4 bg-light">
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>